### PR TITLE
chore(CI): simplify testing strategy

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Comment by ota-meshi** [comment]
The devDependencies espree github protocol seems to be in error, but I don't know why it doesn't work 🤔

**Comment by MichaelDeBoey** [comment]
@ota-meshi I can't get it running locally either for the same reason, but some tests were passing and previous commits were passing as well 🤔

**Comment by ota-meshi** [comment]
It looks like were using espree's github protocol while developing class-fields support.
What are your thoughts on using espree version 8 instead? It doesn't support Node10 but with our luck it might work.

**Comment by MichaelDeBoey** [comment]
@ota-meshi I've updated the `espree` hash to https://github.com/eslint/espree/commit/e71162c0842f683ca71bc34b70142496681b3674, as that's the merged version of the commit it was pointing to before (https://github.com/eslint/espree/pull/486/commits/1c744b3a602b783926344811a9459b92afe57444)

**Comment by MichaelDeBoey** [comment]
@ota-meshi Not testing on Node v10.0.0 _or_ ESLint v5 seems to get this passing.
As I was already planning on removing official support for ESLint v5 & Node v10, I think it's OK to not test against it anymore & get this one merged.

**Review by ota-meshi — APPROVED** [review]
Thank you for working on this and looking into it

**Pull request merged**
