### PR TITLE
chore(docs): add site theme for dark mode

### LINKED ISSUE #83: [doc pages] Consider using a different link color in dark mode
The color for links in dark mode is very dark, which makes them hard to read.

image image

### PR DESCRIPTION
**Pull request by ota-meshi**
This PR adds a dark mode theme to the documentation site.

close #83

### CODE REVIEW

**Comment by ota-meshi** [comment]
Thank you for pointing out.
But the custom container theme is using the vitepress default theme. 
It seems that it is still being improved frequently even now, so I would like to deal with it only if there is a problem even after it becomes GA.
https://github.com/vuejs/vitepress/pull/1989

**Comment by RunDevelopment** [comment]
I'll make them an issue.

**Review by RunDevelopment — APPROVED** [review]

**Comment by ota-meshi** [comment]
@RunDevelopment  Thank you for checking this PR!

**Comment by MichaelDeBoey** [comment]
@ota-meshi Can we have this in our other repos as well please?

**Comment by ota-meshi** [comment]
We could use the same theme in another repo, but I think `eslint-utils` and `eslint-plugin-es-x` are the only repos currently using `vitepress` on the documentation site. If we also replace `vuepress` with `vitepress` in other repo, we can use the same theme.

**Pull request merged**
