### PR TITLE
fix: allow pre-releases of ESLint 9

### PR DESCRIPTION
**Pull request by voxpelli**
Fixes eslint-community/eslint-utils#183, but with the caveats mentioned in https://github.com/npm/rfcs/pull/397#issuecomment-1987224770 :

> 1. It may automatically install a pre-release
> 2. It only allows pre-releases of `9.0.0`, not of eg. `9.0.1` or `10.0.0`, making it an ever moving target

I think the automatic installation of a pre-release is less of an issue for this module than for eg https://github.com/eslint-community/eslint-plugin-n/issues/197 as `@eslint-community/eslint-utils` is never installed by an end-user directly, only indirectly through other plugins.

For eg `eslint-plugin-n` it may be a deal breaker

### CODE REVIEW

**Review by ota-meshi — CHANGES_REQUESTED** [review]
I think we need to make a pull request to the `beta` branch to release it as a beta version.
However, before that, we may need to recreate the `beta` branch.

**Comment by voxpelli** [comment]
@ota-meshi I think this can be merged and released in stable, shouldn't be an issue for `eslint-utils`?

**Comment by ota-meshi** [comment]
Hmmm. I am not sure about that. I would think that anything that works with a non-stable version is not a stable version.

**Comment by voxpelli** [comment]
Depends on what the intention of `>=8.0.0` is, if it is meant to say:

> We we will work with all future stable versions

Or if it is to say:

> We we will work with all future versions

Sadly npm have no way to express the latter (see https://github.com/npm/rfcs/pull/397), hence why this workaround is needed if the latter is what we want to convey, and that's what I think we should convey.

We should never claim to be incompatible with a future release unless we know to be incompatible, as that causes the issues that eg @fisker sees in #183

**Comment by ota-meshi** [comment]
Hmm. However, I'm still not sure. eslint-plugin-unicorn (pull request) also does not include 9.0.0-0 in `peerDependencies`. Why does only eslint-utils need to include 9.0.0-0?

https://github.com/sindresorhus/eslint-plugin-unicorn/pull/2250/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R102

**Comment by voxpelli** [comment]
Do you have a better solution before something like https://github.com/npm/rfcs/pull/397 arrives and allows for peer dependency ranges to match _all_ future version rather than just _stable_ future versions?

Would of course be great to get @fisker's point of view on this solution as well, but since `eslint-utils` is a dependency of many plugins it makes sense that it does the first move in enabling ESLint 9 pre-releases

**Comment by voxpelli** [comment]
I did request guidance from ESLint itself here: https://github.com/eslint/eslint/issues/18093#issuecomment-1987246301

Maybe I should promote that into an issue on its own

**Comment by fisker** [comment]
> eslint-plugin-unicorn (pull request) also does not include 9.0.0-0 in peerDependencies. Why does only eslint-utils need to include 9.0.0-0?

I don't think they are the same, `peerDependencies` will be used when install `eslint-plugin-unicorn`, eslint can be installed because it's in `devDependencies`, and it's `peerDependencies` (if there are) can be satisfied, but  `@eslint-community/eslint-utils`'s `peerDependencies` are not. 

I'm pretty sure if we release/install `eslint-plugin-unicorn` directly with that PR, `eslint-plugin-unicorn` can't be installed either.

**Comment by fisker** [comment]
A reminder: `npm publish --tag XXX` also can release a version from local if you have npm access.

**Comment by ota-meshi** [comment]
@fisker Are you in favor of releasing eslint-utils as a beta version?

I think we have a workflow that allows us to pre-release using the `beta` branch.
https://github.com/eslint-community/eslint-utils/blob/6a7a3f3cc1b53289906d9b9216fda51be171940c/.github/workflows/ci.yml#L124

**Comment by fisker** [comment]
> Are you in favor of releasing eslint-utils as a beta version?

Just need a version, not really care the number.

**Review by ota-meshi — APPROVED** [review]
> since eslint-utils is a dependency of many plugins it makes sense that it does the first move in enabling ESLint 9 pre-releases

I agree with you on that. I think it would be better to pre-release eslint-utils if possible, but I'm not strongly stick to it.

**Comment by harryzcy** [comment]
From https://github.com/eslint-community/eslint-utils/issues/183#issuecomment-2040758920

> It looks like ESLint 9 is released, so matching pre-releases is no longer necessary.

**Pull request closed without merging**
