### PR TITLE
fix!: drop support for ESLint older than 8

### PR DESCRIPTION
**Pull request by voxpelli**
Fixes eslint-community/eslint-utils#233

Companion PR to #234

Opted to not specify any specific minimum minor version for some reason:

* Wasn't done in the old version ranges
* No clear candidate from https://github.com/eslint-community/eslint-utils/issues/233#issuecomment-2355754090 – either one of `>=8.23.0`, `>=8.56.0`, `^8.57.0` would make sense – but would require needless bumps by users of eslint-utils
* Not clear that there are something in the code of `eslint-utils` that requires a newer version

I guess `>=8.23.0` could make sense as that's where the new flat config format was introduced, https://eslint.org/blog/2022/08/eslint-v8.23.0-released/, any opinions?

### CODE REVIEW

**Comment by voxpelli** [comment]
@MichaelDeBoey How does the auto-release handle the merge of two PR:s like this and #234? Will there be a double bump in the major version?

**Review by MichaelDeBoey — CHANGES_REQUESTED** [review]
We should update GitHub workflows as well

**Comment by voxpelli** [comment]
> We should update GitHub workflows as well

True, any opinion on the change itself? Or response to my question? :)

**Comment by MichaelDeBoey** [comment]
@voxpelli To answer your question: you should create a separate branch (if it's called `alpha` or `beta`, you also release an alpha/beta release to NPM) and merge these PRs into that new branch

Once all breaking changes are done, you can merge the new branch into `main` and you'll only have 1 major release.

If you merge both PRs directly to main, it could be that you're release 2 major versions, depending on how quick you are

**Comment by MichaelDeBoey** [comment]
Superseded by #243

**Pull request closed without merging**
